name: .NET Core

on:
  push:
    branches: [ sriharshabammidi-patch-1 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      working-directory: BookMyTicketsBackend
      run: dotnet restore
    - name: Build
      working-directory: BookMyTicketsBackend
      run: dotnet build --configuration Release --no-restore
